### ISSUE TITLE
dontmock the actions and stores ?

### ISSUE THREAD

**Issue by antoineverger** [awei01/fluxxor-test-utils#7]
Hi guys,

you did a pretty good job on this test-utils ! It´s very helpful.

Nevertheless, here is my problem : when creating my fakeflux and setting the stores and actions I´d like to mock, I proceed as described in the documentation : 

```javascript
var FooStore = require('.../wherever/RealFooStoreToMock')

var fakeFlux = FluxxorTestUtils.fakeFlux({ Foo: new FooStore() }, { doFooAction: function() { } })
fakeFlux.genMocksForStoresAndActions()
```

Then if I try to do that : 
```javascript
fakeFlux.stores.Foo.anExistingPublicMethodOfTheStore.mockReturnValue("this is a nice mocked value")
```
I get that message :
```
TypeError: Cannot call method 'mockReturnValue' of undefined
```
Funny thing, if I add a don´t mock for actions and stores classes that I require like this :
```javascript
jest.dontMock('.../wherever/RealFooStoreToMock')
// same for the action
```
Everything runs without error.
Is that something normal, I´m pretty new with all the flux so I might be completely blind on what I´m doing.

Regards,

Antoine

**Comment by awei01** [comment]
Hi, thanks for the report. Sorry, but it's been a while since I've looked at react stuff... But, I'll try to help debug the issue. Can you create a gist or something w/ your test code?

You could also do a console.log of the fakeFlux.stores object (or fakeFlux.stores.Foo) to help debug.

What do your `jest.dontMock` statements look like at the top of your test file?

**Comment by awei01** [comment]
closing due to no response.
